*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LSCTS_VARV02 .

FUNCTION $$UNIT$$ SCTS_GET_AIM_TRACE_REMOTE

    IMPORTING
       VALUE(IV_WITH_PUTTB_SHD) TYPE !BOOLE_D DEFAULT SPACE
    TABLES
       !ET_AIM_TRACE STRUCTURE !CTS_AIM_TRACE
       !ET_AIM_TRC_OBJ STRUCTURE !CTS_AIM_TRC_OBJ
       !ET_AIM_TRC_STM STRUCTURE !CTS_AIM_TRC_STM
       !ET_PUTTB_SHD STRUCTURE !PUTTB_SHD.