*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SCTS_HTA_DEPLOY

    IMPORTING
       REFERENCE(IV_TARCLIENT) TYPE !MANDT
       REFERENCE(IV_IS_UPGRADE) TYPE !TRPARI-W_UPGRADE
    TABLES
       !TT_E071 TYPE !TR_OBJECTS
       !TT_E071K TYPE !TR_KEYS
       !TT_ERROR_LIST TYPE !E071_T OPTIONAL .