*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LSCTS_HTA_TRANSU01.
                    "SCTS_HTA_DEPLOY
INCLUDE LSCTS_HTA_TRANSU02.
                    "SCTS_HTA_UNDEPLOY
INCLUDE LSCTS_HTA_TRANSU03.
                    "SCTS_HTA_HANA_MIGRATION