PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !PV_PACK MODULE %_PV_PACK .

FIELD !PV_SUB MODULE %_PV_SUB .


CHAIN.
  FIELD PV_PACK .
  FIELD PV_SUB .
    MODULE %_BLOCK_1000000.
ENDCHAIN.

CHAIN.
  FIELD PV_PACK .
  FIELD PV_SUB .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD PV_PACK MODULE %_PV_PACK_VAL .